export const mockPhishingData = [
  {
    id: 1,
    email: "suspicious1@example.com",
    status: "Detected",
    date: "2023-11-01",
    risk: "High",
  },
  {
    id: 2,
    email: "suspicious2@example.com",
    status: "Blocked",
    date: "2023-11-02",
    risk: "Medium",
  },
  {
    id: 3,
    email: "suspicious3@example.com",
    status: "Quarantined",
    date: "2023-11-03",
    risk: "High",
  },
  {
    id: 4,
    email: "suspicious4@example.com",
    status: "Detected",
    date: "2023-11-04",
    risk: "Low",
  },
  {
    id: 5,
    email: "suspicious5@example.com",
    status: "Blocked",
    date: "2023-11-05",
    risk: "Medium",
  },
  {
    id: 6,
    email: "suspicious6@example.com",
    status: "Quarantined",
    date: "2023-11-06",
    risk: "High",
  },
  {
    id: 7,
    email: "suspicious7@example.com",
    status: "Detected",
    date: "2023-11-07",
    risk: "Low",
  },
];
